# Generated by Django 4.2.5 on 2023-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_entregable_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='link',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
